# Qui-Quadrado

O teste do qui-quadrado é utilizado para determinar se há uma associação significativa entre duas variáveis categóricas.<br>
Ele compara as frequências observadas com as frequências esperadas em uma tabela de contingência. 
<a url = "https://medium.com/@matheusventura/teste-qui-quadrado-a95cb5ba8c66">ref</a>

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

**Criando uma Tabela de Contingência**

Primeiro, precisamos de uma tabela de contingência, que mostra a contagem de ocorrências para cada combinação de categorias das variáveis.

Exemplo de tabela de contingência (dados fictícios sobre frequência de uma pesquisa):

In [2]:
# Criando uma tabela de contingência de exemplo
dados = {
    'Categoria_A': [10, 20, 30],
    'Categoria_B': [20, 15, 25],
    'Categoria_C': [30, 35, 15]
}

# Convertendo para DataFrame
df = pd.DataFrame(dados, index=['Grupo_1', 'Grupo_2', 'Grupo_3'])
print(df)

         Categoria_A  Categoria_B  Categoria_C
Grupo_1           10           20           30
Grupo_2           20           15           35
Grupo_3           30           25           15


**Executando o Teste Qui-Quadrado**

Usamos a função chi2_contingency da scipy para realizar o teste qui-quadrado.

In [3]:
# Calculando o teste qui-quadrado
chi2, p, dof, expected = chi2_contingency(df)

print("Qui-Quadrado:", chi2)
print("p-valor:", p)
print("Graus de Liberdade:", dof)
print("Frequências Esperadas:")
print(expected)


Qui-Quadrado: 19.444444444444443
p-valor: 0.0006426541863608164
Graus de Liberdade: 4
Frequências Esperadas:
[[18. 18. 24.]
 [21. 21. 28.]
 [21. 21. 28.]]


**↑ Interpretação dos Resultados**
* **Qui-Quadrado:** O valor do qui-quadrado calculado.
* **p-valor:** A probabilidade de observar um valor tão extremo quanto o observado, assumindo que a hipótese nula é verdadeira. Um p-valor menor que 0.05 geralmente indica que podemos rejeitar a hipótese nula.
* **Graus de Liberdade:** O número de categorias menos um, ajustado para o número de variáveis.
* **Frequências Esperadas:** A tabela de frequências esperadas sob a hipótese nula.

**❇️ Exemplo:**

In [ ]:
#*segundo valor é o pvalue
#Valor de p maior que 0,05 não há evidências de diferença significativa (hipótese nula): não há diferença significativa
novela = np.array([[19, 6], [43, 32]])
novela

array([[19,  6],
       [43, 32]])

In [5]:
chi2_contingency(novela)

Chi2ContingencyResult(statistic=np.float64(2.037351443123939), pvalue=np.float64(0.15347667161786666), dof=1, expected_freq=array([[15.5,  9.5],
       [46.5, 28.5]]))

In [6]:
#Podemos rejeitar a hipótese nula em favor da hipótese alternativa: há diferença significativa
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [7]:
chi2_contingency(novela2)

Chi2ContingencyResult(statistic=np.float64(6.461538461538461), pvalue=np.float64(0.011023416388221425), dof=1, expected_freq=array([[16.25,  8.75],
       [48.75, 26.25]]))