In [1]:
import numpy as np

In [4]:
# Criar uma matriz unidimensional → ARRAY:
matriz = np.array([12, 34, 26, 18, 10])
print(matriz)
print(type(matriz))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [6]:
# Criar uma matriz (ARRAY) com um type específico:
matriz_float = np.array([1, 2, 3], dtype = np.float64)
print(matriz_float)
print(type(matriz_float))

matriz_int = np.array([1, 2, 3], dtype = np.int32)
print(matriz_int)
print(type(matriz_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# Mudar o tipo da matriz (ARRAY):
