# Numpy: 

É a biblioteca fundamental de python, usado para executar computação científica. Ele fornece matrizes (arrays) multidimensionais de alto desempenho e ferramentas para lidar com eles. 
Uma matriz numpy é uma grade de valores (do mesmo tipo) que são indexados por uma tupla de inteiros positivos, arrays numpy são rápidos, fáceis de entender e dão aos usuários o direito de realizar cálculos entre os arrays.

https://acervolima.com/diferenca-entre-pandas-vs-numpy/



In [1]:
# Importar NUMPY e apelidar como NP:
import numpy as np

In [2]:
# Criar uma Matriz Unidimensional → ARRAY:
matriz = np.array([12, 34, 26, 18, 10])
print(matriz)
print(type(matriz))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [3]:
# Criar uma matriz (ARRAY) com um type específico:
matriz_float = np.array([1, 2, 3], dtype = np.float64)
print(matriz_float)
print(type(matriz_float))

matriz_int = np.array([1, 2, 3], dtype = np.int32)
print(matriz_int)
print(type(matriz_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# Converter o tipo da matriz (ARRAY):
# De float
matriz_nova = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(matriz_nova)

# Para int
matriz_nova_int = matriz_nova.astype(np.int32)
print(matriz_nova_int)

# O inverso também pode ser feito:
mt1 = np.array([1, 2, 3, 4])
print(mt1)
mt2 = mt1.astype(float)
print(mt2)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]
[1 2 3 4]
[1. 2. 3. 4.]


In [5]:
# Criar uma Matriz Bidimensional → ARRAY:
matriz_bidimensional = np.array([[7, 2 , 23], [12, 27, 4], [5, 34, 23]])
print(matriz_bidimensional)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [6]:
# Criar Matrizes Tipificadas:

# Matriz Vazia: significa que elas começam não inicializadas (não que são vazias):
vazio = np.empty([3, 2], dtype = int)
print(vazio, '\n')

# Matriz com valores zerados:
zero = np.zeros([4, 3])
print(zero, '\n')

# Matriz com valores em um:
um = np.ones([5, 7])
print(um, '\n')

# Matriz com valores apenas na diagonal:
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# Criar números aleatórios para simulações → RANDOM:

# Números entre 0 e 1:
random1 = np.random.random(5)
print(random1, '\n')

# Números aleatórios com distribuição norlam contendo negativos:
random2 = np.random.randn(5)
print(random2, '\n')

# Números aleatóricos com 3 linhas x 4 colunas:
random3 = 10 * np.random.random((3, 4)) # ← multiplica-se por 10 para o número ficar tão pequeno
print(random3, '\n')

[0.16392736 0.42400148 0.28381087 0.91110537 0.81035129] 

[ 0.9643716  -0.40281659 -2.28764441 -0.4060029  -0.20843205] 

[[4.64094775 6.72357857 1.96836456 2.61083271]
 [6.49358074 5.067283   2.48986799 2.68255526]
 [6.67505425 7.06599472 3.77509909 4.41249811]] 



In [8]:
# Gerar números aleatórios a partir de sementes estáticas:
semente = np.random.default_rng(1)
aleatorio1 = semente.random(3)
print(aleatorio1)

# Agora em números inteiros:
aleatorio2 = semente.integers(10, size = (3, 4))
print(aleatorio2)


[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [9]:
# Remover repetições e deixar dados únicos → UNIQUE:
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [10]:
# Criar uma Matriz Bidimensional → ARRAY:
k = np.array([[17, 22, 43], [27, 22, 43], [15, 24, 32]])
print(k, '\n')

# Mostrar um elemebto específico da matriz:
print(k[1][0], '\n') # ← [linha] e [coluna]

# Mostrar o tamanho das dimensões da matriz:
print(k.shape)

[[17 22 43]
 [27 22 43]
 [15 24 32]] 

27 

(3, 3)


In [17]:
# Funções Matemáticas na Matriz Bidimensional:

# Maior → MAX:
print(k.max())

# Menor → MIN:
print(k.min())

# Somar → SUM:
print(k.sum())

# Média → MEAN:
print(round(k.mean(),3)) # ← Arredondar → ROUND(x, 2)

# Desvio Padrão (Standard Deviation) → STD:
print(round(k.std(), 4))

# Raiz Quadrada → SQRT:
print(np.sqrt(k))

# Exponencial → EXP:
print(np.exp(k)) # ← calcula a partir da constante de Euler = 2,718281 elevado à variável

43
15
245
27.222
9.6584
[[4.12310563 4.69041576 6.55743852]
 [5.19615242 4.69041576 6.55743852]
 [3.87298335 4.89897949 5.65685425]]
[[2.41549528e+07 3.58491285e+09 4.72783947e+18]
 [5.32048241e+11 3.58491285e+09 4.72783947e+18]
 [3.26901737e+06 2.64891221e+10 7.89629602e+13]]


In [21]:
# Extrair elementos da matriz → ARRAY:
m = np.array([101, 102, 103, 104, 105, 106])
print(m, '\n')

# Exibir pela posição:
print(m[1])

# Exibir dentro de um intervalo:
print(m[0:2])

# Exibir tudo a partir de uma posição:
print(m[1:])

# Exibir a partir do final de determinarda posição:
print(m[-3:])

[101 102 103 104 105 106] 

102
[101 102]
[102 103 104 105 106]
[104 105 106]


In [30]:
# Extração de linhas e colunas:
mm = np.array([[4, 5], [6, 1], [7, 4]])
print(mm, '\n')

print('Apenas a linha 1: ', mm[0, :])
print('Apenas a linha 2: ', mm[1, :])
print('Apenas a linha 3: ', mm[2, :], '\n')

print('Apenas a coluna 1: ', mm[:, 0])
print('Apenas a coluna 2: ', mm[:, 1], '\n')


[[4 5]
 [6 1]
 [7 4]] 

Apenas a linha 1:  [4 5]
Apenas a linha 2:  [6 1]
Apenas a linha 3:  [7 4] 

Apenas a coluna 1:  [4 6 7]
Apenas a coluna 2:  [5 1 4] 



In [40]:
# Somar e Multiplicar Matrizes:
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

# SOMAR:
soma = n + o
print(soma, '\n')

# MULTIPLICAR:
multiplica = n * o
print(multiplica, '\n')

# Exemplo com tamanhos diferentes de matrizes:
p = np.array([[10, 20], [30, 40], [50, 60]])
q = np.array([20, 10])
print(p+q)

[[2 3]
 [4 5]] 

[[1 2]
 [3 4]] 

[[30 30]
 [50 50]
 [70 70]]


In [47]:
# Criar uma matriz com 15 elementos → ARANGE:
# Definir forma da matriz 3 x 5 → RESHAPE:
f = np.arange(15).reshape(3, 5)
print(f, '\n')

# Transposição → T:
g = f.T
print(g, '\n')

# OU Transposição → TRANSPOSE:
h = f.transpose(1, 0)
print(g)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [52]:
#Expressões Lógicas:
# Criar uma matriz aleatória 4x4:
v = np.random.randn(4, 4)
print(v, '\n')

# Validar maiores e menores que 0:
x = (v > 0)
print(x, '\n')

# Substituir números por 1 e -1 a partir da validação:
z = np.where(x > 0, 1, -1)
print(z)

[[-0.45876115  0.34998309  1.84639697 -2.27202358]
 [ 0.21599994 -0.04122392 -0.12532667  0.14965792]
 [-0.94770351 -1.27255531 -1.65489434  1.50889998]
 [-0.10388202  0.37633408  0.83226838  0.36872849]] 

[[False  True  True False]
 [ True False False  True]
 [False False False  True]
 [False  True  True  True]] 

[[-1  1  1 -1]
 [ 1 -1 -1  1]
 [-1 -1 -1  1]
 [-1  1  1  1]]
