In [2]:
# Importar NUMPY e apelidar como NP:
import numpy as np

In [3]:
# Criar uma Matriz Unidimensional → ARRAY:
matriz = np.array([12, 34, 26, 18, 10])
print(matriz)
print(type(matriz))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
# Criar uma matriz (ARRAY) com um type específico:
matriz_float = np.array([1, 2, 3], dtype = np.float64)
print(matriz_float)
print(type(matriz_float))

matriz_int = np.array([1, 2, 3], dtype = np.int32)
print(matriz_int)
print(type(matriz_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# Converter o tipo da matriz (ARRAY):
# De float
matriz_nova = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(matriz_nova)

# Para int
matriz_nova_int = matriz_nova.astype(np.int32)
print(matriz_nova_int)

# O inverso também pode ser feito:
mt1 = np.array([1, 2, 3, 4])
print(mt1)
mt2 = mt1.astype(float)
print(mt2)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]
[1 2 3 4]
[1. 2. 3. 4.]


In [10]:
# Criar uma Matriz Bidimensional → ARRAY:
matriz_bidimensional = np.array([[7, 2 , 23], [12, 27, 4], [5, 34, 23]])
print(matriz_bidimensional)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [14]:
# Criar Matrizes Tipificadas:

# Matriz Vazia: significa que elas começam não inicializadas (não que são vazias):
vazio = np.empty([3, 2], dtype = int)
print(vazio, '\n')

# Matriz com valores zerados:
zero = np.zeros([4, 3])
print(zero, '\n')

# Matriz com valores em um:
um = np.ones([5, 7])
print(um, '\n')

# Matriz com valores apenas na diagonal:
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
# Criar números aleatórios para simulações → RANDOM:

# Números entre 0 e 1:
random1 = np.random.random(5)
print(random1, '\n')

# Números aleatórios com distribuição norlam contendo negativos:
random2 = np.random.randn(5)
print(random2, '\n')

# Números aleatóricos com 3 linhas x 4 colunas:
random3 = 10 * np.random.random((3, 4)) # ← multiplica-se por 10 para o número ficar tão pequeno
print(random3, '\n')

[0.18134306 0.19414264 0.97667784 0.38279102 0.4475802 ] 

[-0.12126358  1.14759164  1.19895209  1.47318074 -0.46348051] 

[[5.09326942 4.93339971 8.94644274 8.63934144]
 [1.69197938 0.98061932 9.16958251 5.28929563]
 [8.98418741 6.86025513 2.33272307 5.67134017]] 



In [32]:
# Gerar números aleatórios a partir de sementes estáticas:
semente = np.random.default_rng(1)
aleatorio1 = semente.random(3)
print(aleatorio1)

# Agora em números inteiros:
aleatorio2 = semente.integers(10, size = (3, 4))
print(aleatorio2)


[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [33]:
# Remover repetições e deixar dados únicos → UNIQUE:
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
# Funções específicas de Numpy:
k = np.array #CONTINUAR AO ACORDAR.