# K-Nearest Neighbors (KNN)

É um algoritmo de aprendizado supervisionado usado para classificação e regressão.

Ele classifica um novo ponto de dado com base nas classes dos K pontos de dados mais próximos no espaço de características. 

Para regressão, a previsão é a média dos valores dos K vizinhos mais próximos.

**Principais Características**
* **Simples de Implementar:** O KNN é fácil de entender e implementar.
* **Versátil:** Funciona bem tanto para classificação quanto para regressão.
* **Dependente de Dados:** O desempenho do KNN pode ser afetado pela escala e distribuição dos dados.

**Passos do Algoritmo KNN**
* **Carregar os Dados:** Obter o conjunto de dados de treinamento e teste.
* **Escolher o Valor de K:** Decidir o número de vizinhos mais próximos.
* **Calcular a Distância:** Medir a distância entre o novo ponto de dados e todos os pontos de dados no conjunto de treinamento.
* **Encontrar os Vizinhos Mais Próximos:** Selecionar os K pontos de dados mais próximos.
* **Prever a Classe ou Valor:** 
    * Para classificação, a classe mais comum entre os vizinhos é escolhida. 
    * Para regressão, a média dos valores dos vizinhos é calculada.

**Considerações ao Escolher o KNN**
* **Valor de K:** Escolher um valor de K apropriado é crucial. 
    * Um K muito pequeno pode levar a um modelo que overfitta os dados de treinamento. 
    * Um K muito grande pode suavizar demais as fronteiras de decisão.
* **Escalonamento:** Sempre escalone os dados quando usar KNN, pois a distância entre os pontos é sensível às magnitudes dos atributos.
* **Complexidade Computacional:** O KNN pode ser computacionalmente intensivo, especialmente com conjuntos de dados muito grandes.

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

❇️ **Exemplo de Classificação com KNN**

In [2]:
# Carregar o conjunto de dados Iris
iris = load_iris()
X, y = iris.data, iris.target

In [3]:
# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
# Padronizar/ escalar os dados
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
# Criar e treinar o modelo KNN
knn = KNeighborsClassifier(n_neighbors=5)  # Usar 5 vizinhos mais próximos
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [6]:
# Fazer previsões
y_pred = knn.predict(X_test)

In [7]:
# Avaliar o modelo
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")


Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Accuracy: 1.00


❇️ **Exemplo de Regressão com KNN**

In [8]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

In [9]:
# Vamos usar um conjunto de dados de exemplo
data = {
    'X': np.arange(1, 11),
    'y': np.array([1.1, 2.0, 3.2, 4.1, 5.3, 6.2, 7.4, 8.2, 9.3, 10.1])
}
df = pd.DataFrame(data)

In [10]:
# Dividir os dados em conjuntos de treinamento e teste
X = df[['X']]
y = df['y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
# Criar e treinar o modelo KNN Regressor
knn_regressor = KNeighborsRegressor(n_neighbors=3)  # Usar 3 vizinhos mais próximos
knn_regressor.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [12]:
# Fazer previsões
y_pred = knn_regressor.predict(X_test)

In [13]:
# Avaliar o modelo
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")


Mean Squared Error: 0.59


❇️ Exemplo: