# Redes neurais são um dos principais métodos para aprendizado de máquina e inteligência artificial. 

 ## Matemática por Trás da Rede Neural
### 🔍 Fórmula do Neurônio
Cada neurônio segue a fórmula matemática básica:

$z=W⋅X+b$

onde:


* $W$ são os pesos das conexões
* $X$ são as entradas (dados de entrada)
* $b$ é o viés (bias)
* $z$ é o soma ponderada antes da ativação

Após isso, aplicamos a função de ativação $f(z):$

* $a=f(z)$

onde 
$a$ é a saída do neurônio.

🔍 Funções de Ativação
As funções de ativação transformam o valor $z$ em um número útil:

* ReLU	→ $f(z) = \max(0,z)$
* Sigmoid	→ $f(z) = \frac{1} {1+e^{−z}}$
* Softmax	→ $f(z)_i​ = \frac{e^z_i} {∑e^{z_j}}$

​
### 🔍 Backpropagation (Ajuste dos Pesos)
O aprendizado acontece ajustando os pesos usando descida do gradiente:

𝑊_novo = 𝑊_antigo − 𝛼 \frac{∂𝐿}{∂𝑊}

onde:
* $α$ é a taxa de aprendizado
* $L$ é a função de perda
* $\frac{∂𝐿}{∂𝑊}$ é o gradiente da perda em relação ao peso


Carregar bibliotecas

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from keras.models import Sequential #modelo
from keras.layers import Dense #camadas
from tensorflow.keras.utils import to_categorical

import pandas as pd
import numpy as np

Carregar dataset e separar os dados para prever e os dados da classe (tipo da planta)

In [18]:
base = datasets.load_iris()
prever = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Como são três tipos de plantas diferentes: 0, 1 e 2, recomenda-se fazer a tranformação para variáveis dummys, ou seja, quando for a planta daquele tipo, aponta o número 1 na coluna referente:
 [a, b, c]
 [0, 0, 1] 

In [19]:
classe_dummy = to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

Separar os dados de treinamento e teste

In [20]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(prever, classe_dummy, test_size=0.3, random_state=0)

Definir os parâmetros do modelo 

🔍 Explicação:
* keras.Sequential(): Define um modelo sequencial.
* Dense(10, activation='relu'): Camada densa com 10 neurônios e ativação ReLU.
* softmax na saída: Para classificação multiclasse.
* categorical_crossentropy: Função de perda para classificação multiclasse.
* optimizer='adam': Otimizador eficiente para deep learning.


🔍 Funções de Ativação
As funções de ativação transformam o valor $𝑧$ em um número útil.

Nome	Fórmula

ReLU	$𝑓(𝑧)=max⁡(0,𝑧)$

Sigmoid	$𝑓(𝑧)=1/1+𝑒−𝑧$

​Softmax $𝑓(𝑧)𝑖=𝑒𝑧𝑖∑𝑒𝑧𝑗$

In [ ]:
# Criar o modelo de rede neural sequencial
modelo = Sequential()  

# Primeira camada oculta (5 neurônios, entrada com 4 neurônios)
modelo.add(Dense(units=5, input_dim=4))  

# Segunda camada oculta (4 neurônios)
modelo.add(Dense(units=4))  

# Camada de saída (3 neurônios, ativação softmax para classificação multiclasse)
modelo.add(Dense(units=3, activation='softmax'))  

C:\Users\Utente\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [22]:
modelo.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#Adam é o algoritmo de otimização para atualizar os pesos e loss = cálculo do erro 
modelo.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [24]:
modelo.fit(X_treinamento, y_treinamento, epochs=1000, validation_data=(X_teste, y_teste))

Epoch 1/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 180ms/step - accuracy: 0.3160 - loss: 6.8419 - val_accuracy: 0.3556 - val_loss: 6.6058
Epoch 2/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.3160 - loss: 6.2757 - val_accuracy: 0.3556 - val_loss: 6.1155
Epoch 3/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3274 - loss: 5.6712 - val_accuracy: 0.3556 - val_loss: 5.6335
Epoch 4/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3545 - loss: 4.6530 - val_accuracy: 0.3556 - val_loss: 5.1595
Epoch 5/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.3379 - loss: 4.5042 - val_accuracy: 0.3556 - val_loss: 4.7002
Epoch 6/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.3681 - loss: 3.6900 - val_accuracy: 0.3556 - val_loss: 4.2732
Epoch 7/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3285 - loss: 3.5021 - val_accuracy: 0.3556 - val_loss: 3.8928
Epoch 8/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3201 - loss: 3.4327 - val_accuracy: 0.4667 - 

In [25]:
previsto = modelo.predict(X_teste)
previsto = (previsto > 0.5)
previsto

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [26]:
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsto_matrix = [np.argmax(t) for t in previsto]

In [27]:
confusao = confusion_matrix(y_teste_matrix, y_previsto_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])

In [30]:
from tensorflow.keras.utils import plot_model
import pydot

# Salvar imagem do modelo
plot_model(modelo, to_file="modelo.png", show_shapes=True, show_layer_names=True)


You must install pydot (`pip install pydot`) for `plot_model` to work.
