# Numpy: 

É a biblioteca fundamental de python, usado para executar computação científica. Ele fornece matrizes (arrays) multidimensionais de alto desempenho e ferramentas para lidar com eles. 
Uma matriz numpy é uma grade de valores (do mesmo tipo) que são indexados por uma tupla de inteiros positivos, arrays numpy são rápidos, fáceis de entender e dão aos usuários o direito de realizar cálculos entre os arrays. <a href = 'https://acervolima.com/diferenca-entre-pandas-vs-numpy/'>referência</a>

**O que é:** Um array em NumPy é uma estrutura de dados usada para armazenar múltiplos valores em uma única variável. Eles são semelhantes às listas, mas são muito mais poderosos e eficientes em termos de desempenho.

**Quais tipos:**

* **1D**: Array de uma dimensão, como uma lista. <br>
`array_1d = np.array([1, 2, 3, 4])`


* **2D:** Array de duas dimensões, como uma matriz (tabelas). <br>
`array_2d = np.array([[1, 2], [3, 4]])`


* **nD:** Arrays de n-dimensões para dados mais complexos. <br>
`array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`

<img src = https://miro.medium.com/v2/resize:fit:4800/format:webp/1*s7Ijt6lfCtqKMxtsleM0-w.png>

**Para que servem:** Arrays em NumPy são usados para realizar operações matemáticas e estatísticas de maneira eficiente. Eles suportam operações vetorizadas, o que significa que você pode realizar cálculos em várias entradas simultaneamente.

**Prós e contras:**

* **Prós:** Desempenho rápido, suporte para operações complexas, eficiente em termos de memória.

* **Contras:** Menos flexíveis que listas nativas do Python para algumas operações básicas, requer o uso da biblioteca NumPy.

**Quando utilizar:** Utilize arrays em NumPy quando precisar de alto desempenho para cálculos matemáticos, estatísticos ou de manipulação de grandes volumes de dados.




## Importar NUMPY e apelidar como NP:


In [ ]:
import numpy as np

## Criar uma Matriz **Unidimensional** ou *array 1D*:

In [8]:
matriz = np.array([12, 34, 26, 18, 10])
print("Forma: ", matriz.shape)
print("Tipo: ", type(matriz))
print("Matriz Unidimencional, axis 0: ", matriz)


Forma:  (5,)
Tipo:  <class 'numpy.ndarray'>
Matriz Unidimencional, axis 0:  [12 34 26 18 10]


### Criar uma matriz (array) com um type específico:

In [45]:
matriz_float = np.array([1, 2, 3], dtype = np.float64)
print(matriz_float)
print(type(matriz_float))

matriz_int = np.array([1, 2, 3], dtype = np.int32)
print(matriz_int)
print(type(matriz_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


### Converter o tipo da matriz (array):

In [46]:
# DE: float
matriz_nova = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(matriz_nova)

# PARA: int
matriz_nova_int = matriz_nova.astype(np.int32)
print(matriz_nova_int)

# O inverso também pode ser feito:
# DE: int
mt1 = np.array([1, 2, 3, 4])
print(mt1)

# PARA: float
mt2 = mt1.astype(float)
print(mt2)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]
[1 2 3 4]
[1. 2. 3. 4.]


### Extrair elementos da matriz → ARRAY:

In [137]:
m = np.array([101, 102, 103, 104, 105, 106])
print("Matriz Index: \n [ 0↓, 1↓, 2↓, 3↓, 4↓, 5↓] \n", m, '\n')

print("Exibir pela posição [1]:", m[1], '\n')

print("Exibir dentro de um intervalo [0:2]:", m[0:2], '\nresgata o valor da coluna 0 e 1; não traz o último valor na coluna 2 \n')

print("Exibir tudo a partir de uma posição [2: ]:", m[2:], '\n')

print("Exibir a partir do final de determinarda posição [-2: ]:", m[-2:])

Matriz Index: 
 [ 0↓, 1↓, 2↓, 3↓, 4↓, 5↓] 
 [101 102 103 104 105 106] 

Exibir pela posição [1]: 102 

Exibir dentro de um intervalo [0:2]: [101 102] 
resgata o valor da coluna 0 e 1; não traz o último valor na coluna 2 

Exibir tudo a partir de uma posição [2: ]: [103 104 105 106] 

Exibir a partir do final de determinarda posição [-2: ]: [105 106]


## Criar uma Matriz **Bidimensional** ou array 2D:

### Criação da matriz 2D:

In [48]:
matriz_bidimensional = np.array([[7, 2 , 23], [12, 27, 4], [5, 34, 23]])
print(matriz_bidimensional)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


### Mostrar um elemebto específico da matriz:

In [63]:
print(matriz_bidimensional[1][0], '\n') # ← [linha] e [coluna]

12 



### Mostrar o tamanho das dimensões da matriz:

In [62]:
print(matriz_bidimensional.shape)

(3, 3)


### Funções Matemáticas na Matriz Bidimensional:
`max`, `min`, `sum`, `mean`, `std`, `sqrt`, `exp`

In [97]:
print("Está é a matriz 2D: \n", matriz_bidimensional, '\n')

# Maior → MAX:
print("Valor máximo de toda a matriz: ", matriz_bidimensional.max(), '\n')

# Menor → MIN:
print("Valor mínimo de toda a matriz: ", matriz_bidimensional.min(), '\n')

# Somar → SUM:
print("A soma de toda a matriz: ", matriz_bidimensional.sum(), '\n')

# Média → MEAN:
print("A média de toda a matriz: ", round(matriz_bidimensional.mean(),3), '\n') # ← Arredondar → ROUND(x, 2)

# Desvio Padrão (Standard Deviation) → STD:
print("O desvio padrão de toda a matriz: ", round(matriz_bidimensional.std(), 4), '\n')

# Raiz Quadrada → SQRT:
print("A raiz quadrada de cada item da matriz: \n", np.sqrt(matriz_bidimensional), '\n')

# Exponencial → EXP:
print("Valor exponencial de cada item da matriz: \n", np.exp(matriz_bidimensional), '\n') # ← calcula a partir da constante de Euler = 2,718281 elevado à variável

Está é a matriz 2D: 
 [[ 7  2 23]
 [12 27  4]
 [ 5 34 23]] 

Valor máximo de toda a matriz:  34 

Valor mínimo de toda a matriz:  2 

A soma de toda a matriz:  137 

A média de toda a matriz:  15.222 

O desvio padrão de toda a matriz:  11.0331 

A raiz quadrada de cada item da matriz: 
 [[2.64575131 1.41421356 4.79583152]
 [3.46410162 5.19615242 2.        ]
 [2.23606798 5.83095189 4.79583152]] 

Valor exponencial de cada item da matriz: 
 [[1.09663316e+03 7.38905610e+00 9.74480345e+09]
 [1.62754791e+05 5.32048241e+11 5.45981500e+01]
 [1.48413159e+02 5.83461743e+14 9.74480345e+09]] 



In [2]:
# Criar Matrizes Tipificadas:

# Matriz Vazia: significa que elas começam não inicializadas (não que são vazias):
vazio = np.empty([3, 2], dtype = int)
print(vazio, '\n')

# Matriz com valores zerados:
zero = np.zeros([4, 3])
print(zero, '\n')

# Matriz com valores em um:
um = np.ones([5, 7])
print(um, '\n')

# Matriz com valores apenas na diagonal:
diagonal = np.eye(5)
print(diagonal)

NameError: name 'np' is not defined

## Criar números aleatórios para simulações → RANDOM:

### Números entre 0 e 1:

In [52]:
random1 = np.random.random(5)
print(random1, '\n')

[0.60770079 0.63473101 0.14659138 0.20230635 0.29386026] 



### Números aleatórios com distribuição norlam contendo negativos:

In [53]:
random2 = np.random.randn(5)
print(random2, '\n')

[ 1.48369578  1.5924015   0.76866796  0.72328951 -0.31309231] 



### Números aleatóricos com 3 linhas x 4 colunas:

In [54]:
random3 = 10 * np.random.random((3, 4)) # ← multiplica-se por 10 para o número ficar tão pequeno
print(random3, '\n')

[[9.39077488 3.98624336 8.68979424 5.31992915]
 [8.93765219 4.55609568 2.52425261 5.827382  ]
 [3.65553493 8.64654385 7.37778117 0.63311947]] 



### Gerar números aleatórios a partir de sementes estáticas:

In [55]:
semente = np.random.default_rng(1)
aleatorio1 = semente.random(3)
print(aleatorio1)

[0.51182162 0.9504637  0.14415961]


### Gerar números aleatórios a partir de números inteiros:

In [56]:
aleatorio2 = semente.integers(10, size = (3, 4))
print(aleatorio2)


[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


### Remover repetições e deixar dados únicos → UNIQUE:

In [57]:
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


### Extração de linhas e colunas:

In [58]:

mm = np.array([[4, 5], [6, 1], [7, 4]])
print(mm, '\n')

print('Apenas a linha 1: ', mm[0, :])
print('Apenas a linha 2: ', mm[1, :])
print('Apenas a linha 3: ', mm[2, :], '\n')

print('Apenas a coluna 1: ', mm[:, 0])
print('Apenas a coluna 2: ', mm[:, 1], '\n')


[[4 5]
 [6 1]
 [7 4]] 

Apenas a linha 1:  [4 5]
Apenas a linha 2:  [6 1]
Apenas a linha 3:  [7 4] 

Apenas a coluna 1:  [4 6 7]
Apenas a coluna 2:  [5 1 4] 



### Somar e Multiplicar Matrizes:

In [50]:

n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

# SOMAR:
soma = n + o
print("Adição: \n", soma, '\n')

# MULTIPLICAR:
multiplica = n * o
print("Multiplicação: \n", multiplica, '\n')

# Exemplo com tamanhos diferentes de matrizes:
q = np.array([15, 10])
p = np.array([[10, 20], [30, 40], [50, 60]])

print("Soma de matrizes diferentes 2D + 1D: \n", q)
print("    + \n",p)
print("    = \n", p+q)

Adição: 
 [[2 3]
 [4 5]] 

Multiplicação: 
 [[1 2]
 [3 4]] 

Soma de matrizes diferentes 2D + 1D: 
 [15 10]
    + 
 [[10 20]
 [30 40]
 [50 60]]
    = 
 [[25 30]
 [45 50]
 [65 70]]


In [60]:
# Criar uma matriz com 15 elementos → ARANGE:
# Definir forma da matriz 3 x 5 → RESHAPE:
f = np.arange(15).reshape(3, 5)
print(f, '\n')

# Transposição → T:
g = f.T
print(g, '\n')

# OU Transposição → TRANSPOSE:
h = f.transpose(1, 0)
print(g)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [61]:
#Expressões Lógicas:
# Criar uma matriz aleatória 4x4:
v = np.random.randn(4, 4)
print(v, '\n')

# Validar maiores e menores que 0:
x = (v > 0)
print(x, '\n')

# Substituir números por 1 e -1 a partir da validação:
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.31423018  0.45788579 -2.27418915 -0.24026108]
 [ 1.95780826  1.58706041 -0.04743356  1.28268667]
 [-1.3456568  -0.31326181  1.17265209 -1.24331944]
 [ 0.766109   -0.25097068 -1.58430482 -0.53685732]] 

[[ True  True False False]
 [ True  True False  True]
 [False False  True False]
 [ True False False False]] 

[[ 1  1 -1 -1]
 [ 1  1 -1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]]


In [18]:
import numpy as np

# Criando uma matriz 3D com a forma (2, 3, 4)
matriz_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(matriz_3d.shape)
print(matriz_3d)


(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
