# Numpy: 

Um array é uma estrutura para armazenar e recuperar dados. Ele fornece matrizes (arrays) multidimensionais de alto desempenho e ferramentas para lidar com eles. 
Uma matriz numpy é uma grade de valores (do mesmo tipo) que são indexados por uma tupla de inteiros positivos, arrays numpy são rápidos, fáceis de entender e dão aos usuários o direito de realizar cálculos entre os arrays.<br> <a href = 'https://acervolima.com/diferenca-entre-pandas-vs-numpy/'>referência</a> | <a href = https://numpy.org/doc/stable/user/absolute_beginners.html> numpy.org </a>

**O que é:** Um array em NumPy é uma estrutura de dados usada para armazenar múltiplos valores em uma única variável. Eles são semelhantes às listas, mas são muito mais poderosos e eficientes em termos de desempenho.

**Quais tipos:**

* **1D**: Array de uma dimensão, como uma lista. <br>
`array_1d = np.array([1, 2, 3, 4])`


* **2D:** Array de duas dimensões, como uma matriz (tabelas). <br>
`array_2d = np.array([[1, 2], [3, 4]])`


* **nD:** Arrays de n-dimensões para dados mais complexos. <br>
`array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`

<img src = https://miro.medium.com/v2/resize:fit:4800/format:webp/1*s7Ijt6lfCtqKMxtsleM0-w.png>

**Para que servem:** Arrays em NumPy são usados para realizar operações matemáticas e estatísticas de maneira eficiente. Eles suportam operações vetorizadas, o que significa que você pode realizar cálculos em várias entradas simultaneamente.

**Prós e contras:**

* **Prós:** Desempenho rápido, suporte para operações complexas, eficiente em termos de memória.

* **Contras:** Menos flexíveis que listas nativas do Python para algumas operações básicas, requer o uso da biblioteca NumPy.

**Quando utilizar:** Utilize arrays em NumPy quando precisar de alto desempenho para cálculos matemáticos, estatísticos ou de manipulação de grandes volumes de dados.

**Restrições:**
* Todos os elementos da matriz devem ser do mesmo tipo de dados.
* Uma vez criado, o tamanho total do array não pode ser alterado.
* A forma deve ser “retangular”, não “irregular”; por exemplo, cada linha de uma matriz 2d deve ter o mesmo número de colunas.




## Matriz **unidimensional** ou array 1D:

**Matriz 1D** (`a`)
* **Definição:** Uma matriz 1D é essencialmente uma lista de valores.
* **Forma** **(**`.shape`**):** (`a,`)
    *  `a`: Número de elementos na matriz.

In [185]:
import numpy as np

In [186]:
matriz_1d = np.array([12, 34, 26, 18, 10])

print("Dimensões: ", matriz_1d.ndim)
print("Forma: ", matriz_1d.shape)
print("Tamanho: ", matriz_1d.size)
print("Tipo: ", type(matriz_1d), matriz_1d.dtype)
print("Matriz Unidimencional, axis (a, ): ", matriz_1d)


Dimensões:  1
Forma:  (5,)
Tamanho:  5
Tipo:  <class 'numpy.ndarray'> int64
Matriz Unidimencional, axis (a, ):  [12 34 26 18 10]


### Manupulação básica

#### Ordenar → SORT

In [187]:
np.sort(matriz_1d)

array([10, 12, 18, 26, 34])

#### Concatenar → CONCATENATE

In [188]:
print("Matrizes 1D:")
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("A  =", a, "& B =", b)
print("AB =", np.concatenate((a, b)))

print("\nMatrizes 2D: ")
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print("X = \n", x, "\n&\nY =\n", y,"\n")
print("XY =\n", np.concatenate((x, y), axis=0))

Matrizes 1D:
A  = [1 2 3 4] & B = [5 6 7 8]
AB = [1 2 3 4 5 6 7 8]

Matrizes 2D: 
X = 
 [[1 2]
 [3 4]] 
&
Y =
 [[5 6]] 

XY =
 [[1 2]
 [3 4]
 [5 6]]


### Criar um array com um type específico

In [189]:
matriz_float = np.array([1, 2, 3], dtype = np.float64)
print(matriz_float, matriz_float.dtype)

matriz_int = np.array([1, 2, 3], dtype = np.int32)
print(matriz_int, matriz_int.dtype)

[1. 2. 3.] float64
[1 2 3] int32


### Converter o tipo da matriz (array):

In [190]:
print("Convertendo de float para int:")
# DE: float
matriz_nova = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(matriz_nova, matriz_nova.dtype)

# PARA: int
matriz_nova_int = matriz_nova.astype(np.int32)
print(matriz_nova_int, matriz_nova_int.dtype)

print("\nO inverso também pode ser feito:\n")
# DE: int
mt1 = np.array([1, 2, 3, 4])
print(mt1, mt1.dtype)

# PARA: float
mt2 = mt1.astype(float)
print(mt2, mt2.dtype)

Convertendo de float para int:
[ 1.4       3.6      -5.1       9.42      4.999999] float64
[ 1  3 -5  9  4] int32

O inverso também pode ser feito:

[1 2 3 4] int64
[1. 2. 3. 4.] float64


### Extrair elementos

In [191]:
m = np.array([101, 102, 103, 104, 105, 106])
print("Matriz Index: \n [ 0↓, 1↓, 2↓, 3↓, 4↓, 5↓] \n", m, '\n')

print("Exibir pela posição [1]:", m[1], '\n')

print("Exibir dentro de um intervalo [0:2]:", m[0:2], '\nresgata o valor da coluna 0 e 1; não traz o último valor na coluna 2 \n')

print("Exibir tudo a partir de uma posição [2: ]:", m[2:], '\n')

print("Exibir a partir do final de determinarda posição [-2: ]:", m[-2:])

Matriz Index: 
 [ 0↓, 1↓, 2↓, 3↓, 4↓, 5↓] 
 [101 102 103 104 105 106] 

Exibir pela posição [1]: 102 

Exibir dentro de um intervalo [0:2]: [101 102] 
resgata o valor da coluna 0 e 1; não traz o último valor na coluna 2 

Exibir tudo a partir de uma posição [2: ]: [103 104 105 106] 

Exibir a partir do final de determinarda posição [-2: ]: [105 106]


### Converter de Array 1D para Array 2D
Você pode usar `np.newaxis `e `np.expand_dims` para aumentar as dimensões do seu array existente.

Usar `np.newaxis` aumentará as dimensões do seu array em uma dimensão quando usado uma vez. Isso significa que um array 1D se tornará um array 2D , um array 2D se tornará um array 3D , e assim por diante.

In [192]:
a1 = np.array([1, 2, 3, 4, 5, 6])
print(a1.shape, a1)

a2 = a1[np.newaxis, :]
print(a2.shape, a2)

a3 = a1[:, np.newaxis]
print(a3.shape, "\n", a3)


(6,) [1 2 3 4 5 6]
(1, 6) [[1 2 3 4 5 6]]
(6, 1) 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Matriz **bidimensional** ou array 2D:

**Matriz 2D** (`a, b`)
* **Definição:** Uma matriz 2D é uma tabela de valores com linhas e colunas.
* **Forma (**`.shape`**):** (`a, b`)
    * `a`: Número de linhas.
    * `b`: Número de colunas.

In [193]:
matriz_2d = np.array([[7, 2 , 23], [12, 27, 4], [5, 34, 23]])

print("Dimensões: ", matriz_2d.ndim)
print("Forma: ", matriz_2d.shape)
print("Tamanho: ", matriz_2d.size)
print("Tipo: ", type(matriz_2d), matriz_2d.dtype)
print("Matriz Unidimencional, axis (a, b): \n", matriz_2d)


Dimensões:  2
Forma:  (3, 3)
Tamanho:  9
Tipo:  <class 'numpy.ndarray'> int64
Matriz Unidimencional, axis (a, b): 
 [[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


### Mostrar um elemento específico da matriz:

In [194]:
print(matriz_2d[1][0], '\n') # ← [linha] e [coluna]

12 



### Funções Matemáticas na Matriz 2d:
`max`, `min`, `sum`, `mean`, `std`, `sqrt`, `exp`

In [195]:
print("# Está é a matriz 2D: \n", matriz_2d, '\n')

# Maior → MAX:
print("# Valor máximo de toda a matriz: ", matriz_2d.max(), '\n')

# Menor → MIN:
print("# Valor mínimo de toda a matriz: ", matriz_2d.min(), '\n')

# Somar → SUM:
print("# A soma de toda a matriz: ", matriz_2d.sum(), '\n')

# Média → MEAN:
print("# A média de toda a matriz: ", round(matriz_2d.mean(),3), '\n') # ← Arredondar → ROUND(x, 2)

# Desvio Padrão (Standard Deviation) → STD:
print("# O desvio padrão de toda a matriz: ", round(matriz_2d.std(), 4), '\n')

# Raiz Quadrada → SQRT:
print("# A raiz quadrada de cada item da matriz: \n", np.sqrt(matriz_2d), '\n')

# Exponencial → EXP:
print("# Valor exponencial de cada item da matriz: \n", np.exp(matriz_2d), '\n') # ← calcula a partir da constante de Euler = 2,718281 elevado à variável

# Está é a matriz 2D: 
 [[ 7  2 23]
 [12 27  4]
 [ 5 34 23]] 

# Valor máximo de toda a matriz:  34 

# Valor mínimo de toda a matriz:  2 

# A soma de toda a matriz:  137 

# A média de toda a matriz:  15.222 

# O desvio padrão de toda a matriz:  11.0331 

# A raiz quadrada de cada item da matriz: 
 [[2.64575131 1.41421356 4.79583152]
 [3.46410162 5.19615242 2.        ]
 [2.23606798 5.83095189 4.79583152]] 

# Valor exponencial de cada item da matriz: 
 [[1.09663316e+03 7.38905610e+00 9.74480345e+09]
 [1.62754791e+05 5.32048241e+11 5.45981500e+01]
 [1.48413159e+02 5.83461743e+14 9.74480345e+09]] 



### Criar Matrizes Tipificadas:

In [196]:
print("# Matriz Vazia: significa que elas começam não inicializadas (não que são vazias):")
vazio = np.empty([3, 2], dtype = int) # os valores se alteram a cada execução
print(vazio, '\n')

print("# Matriz com valores zerados:")
zero = np.zeros([4, 3])
print(zero, '\n')

print("# Matriz com valores em um:")
um = np.ones([5, 7])
print(um, '\n')

print("# Matriz com valores apenas na diagonal:")
diagonal = np.eye(5)
print(diagonal)

# Matriz Vazia: significa que elas começam não inicializadas (não que são vazias):
[[1 2]
 [3 4]
 [5 6]] 

# Matriz com valores zerados:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

# Matriz com valores em um:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]] 

# Matriz com valores apenas na diagonal:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Matriz **Tridimensional** ou array 3D

**Matriz 3D** (`a, b, c`)
* **Definição:** Uma matriz 3D é uma coleção de tabelas 2D empilhadas.
* **Forma (**`.shape`**):** (`a, b, c`)
    * `a`: Número de **blocos** (ou camadas) ⚠️
    * `b`: Número de linhas em cada bloco
    * `c`: Número de colunas em cada bloco

### Visualização da Estrutura:

**A matriz 3D pode ser visualizada como dois ou mais blocos 2D empilhados.**

In [197]:
matriz_3d = np.array([
    [[1, 2, 13, 14], [3, 4, 15, 16], [5, 6, 17, 18]],
    [[7, 8, 19, 20], [9, 10, 21, 22], [11, 12, 23, 24]]
])
print("#Array 3D: \n", matriz_3d, "\n",
     " \n#Dimensões: ", matriz_3d.ndim, 
     "\n#Forma: " , matriz_3d.shape,
     "\n#Tamaho: ", matriz_3d.size,
     "\n#Tipo: ", matriz_3d.dtype, 
     "\n a = 2 blocos \n b = 3 linhas por bloco \n c = 4 colunas por bloco")

#Array 3D: 
 [[[ 1  2 13 14]
  [ 3  4 15 16]
  [ 5  6 17 18]]

 [[ 7  8 19 20]
  [ 9 10 21 22]
  [11 12 23 24]]] 
  
#Dimensões:  3 
#Forma:  (2, 3, 4) 
#Tamaho:  24 
#Tipo:  int64 
 a = 2 blocos 
 b = 3 linhas por bloco 
 c = 4 colunas por bloco


### Acessando Elementos


In [198]:
print("# Apenas o primeiro bloco (índice ou index 0): \n", matriz_3d[0]) 
# Saída: [[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]]

# Apenas o primeiro bloco (índice ou index 0): 
 [[ 1  2 13 14]
 [ 3  4 15 16]
 [ 5  6 17 18]]


In [199]:
print("# Apenas o elemento (ou valor ou item) na posição \n (a bloco = 1, b linha = 2, c coluna = 3): \n", matriz_3d[1, 2, 3]) 
# Saída: [[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]]

# Apenas o elemento (ou valor ou item) na posição 
 (a bloco = 1, b linha = 2, c coluna = 3): 
 24


<a href="https://ibb.co/MP1qMMT"><img src="https://i.ibb.co/ZcgyWWs/3d.png" alt="3d" border="0"></a>

### Operações

In [200]:
matriz_somada = matriz_3d + 10
print("Somar 10 a todos os elementos: \n", matriz_somada)


Somar 10 a todos os elementos: 
 [[[11 12 23 24]
  [13 14 25 26]
  [15 16 27 28]]

 [[17 18 29 30]
  [19 20 31 32]
  [21 22 33 34]]]


## Demais abordagens e usos

### Indexação e Fatiamento

<img src = https://numpy.org/doc/stable/_images/np_indexing.png
    width = "900"
    weight = "450">

In [201]:
#Por exemplo, se você começar com esta matriz:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("# Matriz 2D:\n", a)

#Você pode imprimir facilmente todos os valores na matriz que são menores que 5:
print("\n# a < 5: ", a[a < 5])

#Você também pode selecionar, por exemplo, números iguais ou maiores que 5 e usar essa condição para indexar uma matriz:
five_up = (a >= 5)
print("\n# a >= 5:", a[five_up])

#Você pode selecionar elementos que são divisíveis por 2:
divisible_by_2 = a[a%2==0]
print("\n# Divisível por 2:", divisible_by_2)

#Ou você pode selecionar elementos que satisfaçam duas condições usando os operadores & e | :
c = a[(a > 2) & (a < 11)]
print("\n# a>2 & a<11:", c)


#Você também pode fazer uso dos operadores lógicos & e | para retornar valores booleanos que especificam se os valores em um array atendem ou não a uma determinada condição (útil com arrays que contêm nomes ou outros valores categóricos):
five_up = (a > 5) | (a == 5)

print("\n# a é maior ou igual a 5?:\n\n", a, "\n\n", five_up)

# Matriz 2D:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

# a < 5:  [1 2 3 4]

# a >= 5: [ 5  6  7  8  9 10 11 12]

# Divisível por 2: [ 2  4  6  8 10 12]

# a>2 & a<11: [ 3  4  5  6  7  8  9 10]

# a é maior ou igual a 5?:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [202]:
print("#Você também pode usar `np.nonzero()` para selecionar elementos ou índices de uma matriz:")
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

print("\n#Você pode usar `np.nonzero()` para imprimir os índices de elementos que são, por exemplo, menores que 5:")
b = np.nonzero(a < 5)
print(b)

# Neste exemplo, uma tupla de arrays foi retornada: uma para cada dimensão. O primeiro array representa os índices de linha onde esses valores são encontrados, e o segundo array representa os índices de coluna onde os valores são encontrados.

#Você também pode usar `np.nonzero()` para selecionar elementos ou índices de uma matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

#Você pode usar `np.nonzero()` para imprimir os índices de elementos que são, por exemplo, menores que 5:
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


### Números aleatórios para simulações → RANDOM:

In [232]:
random1 = np.random.random(5)
print("Números entre 0 e 1:\n", random1, '\n')

random2 = np.random.randn(5)
print("Números aleatórios com distribuição normal contendo negativos:\n", random2, '\n')

random3 = 10 * np.random.random((3, 4)) # ← multiplica-se por 10 para o número ficar tão pequeno
print("Números aleatóricos com (linhas a = 3, colunas b = 4):\n", random3, '\n')

semente = np.random.default_rng(1)
aleatorio1 = semente.random(3)
print("Gerar números aleatórios a partir de sementes estáticas:\n", aleatorio1, '\n')

aleatorio2 = semente.integers(10, size = (3, 4))
print("Gerar números aleatórios a partir de números inteiros:\n", aleatorio2, '\n')


Números entre 0 e 1:
 [0.26924422 0.68553886 0.88979413 0.72997449 0.91997506] 

Números aleatórios com distribuição normal contendo negativos:
 [-2.52706749 -0.68607546 -0.60296629 -0.23137566 -1.12715931] 

Números aleatóricos com (linhas a = 3, colunas b = 4):
 [[1.14033184 4.38214668 2.21495484 4.54010699]
 [9.637297   0.41779383 2.76071724 9.65046339]
 [5.40107952 4.13477629 1.67740895 1.55985948]] 

Gerar números aleatórios a partir de sementes estáticas:
 [0.51182162 0.9504637  0.14415961] 

Gerar números aleatórios a partir de números inteiros:
 [[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]] 



### Remover repetições e deixar dados únicos → UNIQUE:

In [208]:
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


### Extração de linhas e colunas:

In [209]:

mm = np.array([[4, 5], [6, 1], [7, 4]])
print(mm, '\n')

print('Apenas a linha 1: ', mm[0, :])
print('Apenas a linha 2: ', mm[1, :])
print('Apenas a linha 3: ', mm[2, :], '\n')

print('Apenas a coluna 1: ', mm[:, 0])
print('Apenas a coluna 2: ', mm[:, 1], '\n')


[[4 5]
 [6 1]
 [7 4]] 

Apenas a linha 1:  [4 5]
Apenas a linha 2:  [6 1]
Apenas a linha 3:  [7 4] 

Apenas a coluna 1:  [4 6 7]
Apenas a coluna 2:  [5 1 4] 



### Operações básicas de matriz:

Digamos, por exemplo, que você criou dois arrays, um chamado “data” e outro chamado “ones” <br>
<img src = https://numpy.org/doc/stable/_images/np_array_dataones.png
    width = "900"
    weight = "450">

In [210]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print("Data: ", data, "\nOnes: ", ones)


Data:  [1 2] 
Ones:  [1 1]


#### Somar
<img src = https://numpy.org/doc/stable/_images/np_data_plus_ones.png
    width = 900
    weight = 450>


In [211]:
print("Data: ", data, "\nOnes: ", ones)
print("\nSoma:", data + ones)

Data:  [1 2] 
Ones:  [1 1]

Soma: [2 3]


#### Subtrair, multiplicar e dividir
<img src = https://numpy.org/doc/stable/_images/np_sub_mult_divide.png
    width = 900
    weight = 450>


In [212]:
print("Data: ", data, "\nOnes: ", ones)

print("\nSubtração:", data - ones)
print("\nMultiplicação:", data * ones)
print("\nDivisão:", data / ones)

Data:  [1 2] 
Ones:  [1 1]

Subtração: [0 1]

Multiplicação: [1 2]

Divisão: [1. 2.]


#### Broadcasting

⚠️ O NumPy entende que a multiplicação deve acontecer com cada célula, ou seja, esse conceito é chamado de broadcasting. <br>

_As dimensões do seu array devem ser compatíveis, por exemplo, quando as dimensões de ambos os arrays são iguais ou quando um deles é 1. Se as dimensões não forem compatíveis, você obterá um ValueError._

<img src = https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png
    width = 900
    weight = 450>


In [213]:
data = np.array([1.0, 2.0])
print(data, "* 1.6 = ", data * 1.6)

[1. 2.] * 1.6 =  [1.6 3.2]


In [214]:
# Exemplo com tamanhos diferentes de matrizes:
q = np.array([15, 10])
p = np.array([[10, 20], [30, 40], [50, 60]])

print("Soma de matrizes diferentes 2D + 1D: \n", q)
print("    + \n",p)
print("    = \n", p+q)

Soma de matrizes diferentes 2D + 1D: 
 [15 10]
    + 
 [[10 20]
 [30 40]
 [50 60]]
    = 
 [[25 30]
 [45 50]
 [65 70]]


In [215]:
#Se você começar com esta matriz:
b = np.array([[1, 10, 15], [2, 20, 25]])
print("Matriz 2D:\n", b)

#Você pode somar sobre o eixo das linhas com:
print("\nSomar números entre linha de cima e linha de baixo [0]:\n", b.sum(axis=0))

#Você pode somar sobre o eixo das colunas com:
print("\nSomar números dentro das mesmas colunas [1]:\n", b.sum(axis=1))

Matriz 2D:
 [[ 1 10 15]
 [ 2 20 25]]

Somar números entre linha de cima e linha de baixo [0]:
 [ 3 30 40]

Somar números dentro das mesmas colunas [1]:
 [26 47]


#### Max, Mix, Mean, Prod, Std, Sum

O NumPy também executa funções de **agregação**. Além de `min`, `max`, e `sum`, você pode facilmente executar `mean` para obter a média, `prod` para obter o resultado da multiplicação dos elementos, `std` para obter o desvio padrão e muito mais.

<img src = https://numpy.org/doc/stable/_images/np_aggregation.png
    width = 900
    weight = 450>

In [216]:
print("Data: ", data)
print("Max: ", data.max())
print("Min: ", data.min())
print("Mean: ", data.mean())
print("Prod: ", data.prod())
print("Std: ", data.std())
print("Sum: ", data.sum())


Data:  [1. 2.]
Max:  2.0
Min:  1.0
Mean:  1.5
Prod:  2.0
Std:  0.5
Sum:  3.0


### Arange, Reshape e Transpose:

#### Criar uma matriz com 15 elementos → ARANGE:

In [217]:
print("# Criar uma matriz com 15 elementos → ARANGE:")
f = np.arange(15)
print(f)

# Criar uma matriz com 15 elementos → ARANGE:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### Definir forma da matriz (a = 3, b = 5) → RESHAPE:

In [218]:
print("# Definir forma da matriz (a = 3, b = 5) → RESHAPE:")
f = np.arange(15).reshape(3, 5)
print(f)

# Definir forma da matriz (a = 3, b = 5) → RESHAPE:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### Transposição (a = 5, b = 3) → TRANSPOSE:

In [219]:
print("# Transposição (a = 5, b = 3) → TRANSPOSE:")
h = f.transpose(1, 0)
print(h, "\n")

print("# OU Transposição (5, 3) → T:")
g = f.T
print(g, '\n')



# Transposição (a = 5, b = 3) → TRANSPOSE:
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

# OU Transposição (5, 3) → T:
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 



### Expressões Lógicas:

#### Criar uma matriz aleatória (4, 4):

In [220]:
print("# Criar uma matriz aleatória (4, 4):")
v = np.random.randn(4, 4)
print(v)

# Criar uma matriz aleatória (4, 4):
[[ 0.27890132  0.51742099  1.33739925  1.58453352]
 [-0.7697697  -0.05496792  1.48125576 -0.54333636]
 [ 0.58677457 -0.47402955  1.84339104 -0.25355905]
 [ 0.63589682 -0.5108078   0.86145316  1.5184381 ]]


#### Validar maiores e menores que 0:

In [221]:
print("# Validar maiores e menores que 0:")
x = (v > 0)
print(x)

# Validar maiores e menores que 0:
[[ True  True  True  True]
 [False False  True False]
 [ True False  True False]
 [ True False  True  True]]


#### Substituir números por 1 e -1 a partir da validação:

In [222]:
print("# Substituir números por 1 e -1 a partir da validação:")
z = np.where(x > 0, 1, -1)
print(z)

# Substituir números por 1 e -1 a partir da validação:
[[ 1  1  1  1]
 [-1 -1  1 -1]
 [ 1 -1  1 -1]
 [ 1 -1  1  1]]


In [223]:
import numpy as np

# Criando uma matriz 3D com a forma (2, 3, 4)
matriz_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(matriz_3d.shape)
print(matriz_3d)


(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
